apiVersion: v1
kind: Service
metadata:
  name: certificate-initializer-injector-webhook-service
  labels:
    app: certificate-initializer-injector
spec:
  ports:
  - port: 8443
    targetPort: 8443
  selector:
    app: certificate-initializer-injector
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: certificate-initializer-injector-configuration
  annotations:
    cert-manager.io/inject-ca-from: default/certificate-initializer-injector-webhook-cert
webhooks:
- clientConfig:
    caBundle: Cg==
    service:
      name: certificate-initializer-injector-webhook-service
      path: /mutate
      port: 8443
      namespace: "default"
  sideEffects: None
  admissionReviewVersions: ["v1beta1"]
  failurePolicy: Fail
  name: mpod.kb.io
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pods
    scope: "Namespaced"
  namespaceSelector:
      matchLabels:
        uipath-injections: "true"